### ISSUE TITLE
why mix-clip implement is different with paper?

### ISSUE THREAD

**Issue by ChenMinQi** [zbh2047/clipping-algorithms#1]
https://github.com/zbh2047/clipping-algorithms/blob/master/algorithm.py#L112
the mix-clip in paper is x(t+1) = x(t) - [lr * min(η, γ/||m(t+1||)]m(t+1) + ... ]
but in the code, it is  p.data.add_(-lr * nu / (1 + sum / gamma * lr), d_p)
why the code implement is this?

**Comment by zbh2047** [comment]
This code implements the "soft" version of mixed clipping. You could read the Appendix F (especially Figure 4) about hard clipping and soft clipping. Hard clipping is easier for a proof, but we find that soft clipping is slightly better than hard clipping (although we just did a course grid search over hyper-parameters). Nevertheless, hard mixed clipping is still much faster than sgd.
